{
    'name': 'Familia',
    'version': '1.0.1',
    'summary': 'Gestiona clientes como familias y miembros de la familia.',
    'author': 'JB Talens',
    'category': 'Sales',
    'images': ['static/description/icon.png'],
    'depends': ['base', 'contacts', 'saldo_favor','sale', 'portal', 'website'],
    'assets': {
    'web.assets_frontend': [
        'familia/static/src/js/portal_family.js',
    ],
},
'qweb': [],
    'data': [
        'security/familia_security.xml',
        'security/ir.model.access.csv',
        'security/familia_record_rules.xml',
        'views/familia_views.xml',
        'views/miembro_familia_views.xml',
        'views/familia_menu.xml',
        'views/res_partner_faller_view.xml',
        'views/partner_server_action.xml',
        'data/partner_titles.xml',
        'views/portal_reserves.xml', 
        'views/portal_my_home_barcode.xml',
        'data/rename_sale_menu.xml',
        'views/portal_no_invoices.xml',
        #'views/portal_family_dropdown.xml',
        'views/portal_family_block.xml',
        'views/portal_family_sidebar.xml',
        'views/portal_manage_member.xml',


    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
    'post_load': None,
    'pre_init_hook': None,
    'post_init_hook': None,
}
